"""Add AlertMessage model for supervisor notifications

Revision ID: 6102a7126948
Revises: 20260604addvillage
Create Date: 2026-06-04 17:53:34.935563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6102a7126948'
down_revision = '20260604addvillage'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anc_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_anc_area'))
        batch_op.create_index('idx_anc_village', ['village'], unique=False)
        batch_op.drop_column('area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anc_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_index('idx_anc_village')
        batch_op.create_index(batch_op.f('idx_anc_area'), ['area'], unique=False)

    # ### end Alembic commands ###
