"""initial migration

Revision ID: ea384d437a10
Revises: 
Create Date: 2026-05-21 10:26:33.196013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea384d437a10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immunization_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_id', sa.String(length=36), nullable=True),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('administered_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('scheduled', 'due', 'given', 'overdue')", name='chk_immunization_status'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccine_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.create_index('idx_immunization_child_id', ['child_id'], unique=False)
        batch_op.create_index('idx_immunization_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_immunization_status', ['status'], unique=False)
        batch_op.create_index('idx_immunization_vaccine_name', ['vaccine_name'], unique=False)

    with op.batch_alter_table('anc_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, server_default='Unnamed'))
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_anc_village'))
        batch_op.drop_index(batch_op.f('idx_anc_visit_number'))
        batch_op.create_index('idx_anc_area', ['area'], unique=False)
        batch_op.drop_column('village')
        batch_op.drop_column('remarks')
        batch_op.drop_column('beneficiary_name')
        batch_op.drop_column('bp')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('hb')
        batch_op.drop_column('visit_number')

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, server_default=sa.text('now()')))
        batch_op.alter_column('mobile',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_children_asha_id'))
        batch_op.drop_index(batch_op.f('idx_children_dob'))
        batch_op.drop_index(batch_op.f('idx_children_gender'))
        batch_op.create_index('idx_children_created_at', ['created_at'], unique=False)
        # Clean up orphaned asha_id values before adding FK
        op.execute('UPDATE children SET asha_id = NULL WHERE asha_id IS NOT NULL AND asha_id NOT IN (SELECT worker_id FROM users)')
        batch_op.create_foreign_key(None, 'users', ['asha_id'], ['worker_id'], ondelete='SET NULL')
        batch_op.drop_column('village')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.create_index('idx_families_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('vaccine_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('visit_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_id', sa.String(length=36), nullable=False))
        batch_op.create_index('idx_visit_child_id', ['child_id'], unique=False)
        batch_op.create_foreign_key(None, 'children', ['child_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_visit_child_id')
        batch_op.drop_column('child_id')

    with op.batch_alter_table('vaccine_entries', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_created_at')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index('idx_families_created_at')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('village', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_children_created_at')
        batch_op.create_index(batch_op.f('idx_children_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('idx_children_dob'), ['dob'], unique=False)
        batch_op.create_index(batch_op.f('idx_children_asha_id'), ['asha_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('mobile',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('area')

    with op.batch_alter_table('anc_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hb', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bp', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('beneficiary_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('village', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_anc_area')
        batch_op.create_index(batch_op.f('idx_anc_visit_number'), ['visit_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_anc_village'), ['village'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('area')
        batch_op.drop_column('name')

    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.drop_index('idx_immunization_vaccine_name')
        batch_op.drop_index('idx_immunization_status')
        batch_op.drop_index('idx_immunization_due_date')
        batch_op.drop_index('idx_immunization_child_id')

    op.drop_table('immunization_records')
    # ### end Alembic commands ###
